name: CodeDumper
version: '${version}'
main: lol.koblizek.codedumper.CodeDumper
api-version: '1.20'
load: STARTUP
commands:
  getclass:
    description: Get details about a class(es)
    usage: /getclass [classes...]
  decompile:
    description: Decompile a class
    usage: /decompile <class>
  classexists:
    description: Check if a class exists
    usage: /classexists [classes...]
  packageinfo:
    description: Get details about a packages
    usage: /packageinfo [package...]